<!doctype html>
<html>
<head>
    <base href="/"/>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>

<body id="panel" data-controller="<?php echo $this->layout()->routes['controller'];?>" data-action="<?php echo $this->layout()->routes['action'];?>" data-id="<?php echo $_GET['id'];?>">

	<header>
	
		<div class="top-menu">
			
			<a data-href="<?php echo $_SERVER['HTTP_REFERER']; ?>" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" class="fa fa-angle-left mobile" aria-hidden="true"></a>
			
			<a class="hamburguer d-sm-none"><i class="fa fa-bars" style="font-size:26px; margin-top:15px;"></i></a>
			
			<a href="/" class="logo ml-sm-4" target="_blank">CONCAD</a>
			
		</div>
	
	</header>
	
	<nav class="nav-menu" id="panel-touch">
	
		<?php if( !empty($this->layout()->me->nome) ): ?>
		<div class="ml-3 mt-3 text-white">
			OLÁ <?php echo mb_strtoupper($this->layout()->me->nome); ?>
		</div>
		<?php endif; ?>
	
		<ul>
		
            <li class="menu-link">
                <a href="/painel/planos">
                    <i class="fa fa-th-list"></i>
                    <span>Planos</span>
                </a>
            </li>

<!--			<li class="menu-link" data-dropdown="true">-->
<!--				-->
<!--				<a href="javascript:;">-->
<!--					<i class="fa fa-headphones"></i> -->
<!--					<span>SAC</span>-->
<!--				</a>-->
<!--				-->
<!--				<ul>-->
<!--					<li><a href="/painel/sac">Atendimentos ativos</a></li>-->
<!--					<li><a href="/painel/sac/atendimentos-arquivados">Atendimentos arquivados</a></li>-->
<!---->
<!--				</ul>-->
<!--				-->
<!--			</li>-->

			<li class="menu-link">
				<a href="/painel/login/logout">
					<i class="fa fa-power-off"></i>
					<span>Sair</span>
				</a>
			</li>
			
		</ul>
		
	</nav>
	
	<section class="content-panel mb-3">
	
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="color-principal" href="/painel">Home</a></li>
                
                <?php if( count($this->layout()->breadcrumb) ): ?>
                    <?php foreach( $this->layout()->breadcrumb as $row ): ?>
                    <li class="breadcrumb-item">
                    	<?php echo $row['link'] != 'javascript:;' ? '<a class="color-principal" href="'.$row['link'].'">'.$row['title'].'</a> ' : $row['title']; ?>
                    </li>
                    <?php endforeach; ?>
                <?php endif; ?>	
                
            </ol>
        </nav>
        
        <div class="filter" id="filter-touch">
        	<div class="container-fluid"></div>
        </div>
        
		<div class="container-fluid animated fadeIn">
			<?php echo $this->message(); ?>
			<?php echo $this->content;?>
		</div>
	
	</section>
	
	<?php echo $this->layout()->modal; ?>
</body>
</html>