<!--LINHA-->
<div class="hr_resultado">
    <hr>
</div>
<!--FIM LINHA-->

<!--BREADCRUMB-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 pagina">
            <ul>
                <li><a href="/">HOME</a></li><i class="fa fa-angle-right"></i>
                <li><a href="javascript:;">MINHA CONTA</a></li><i class="fa fa-angle-right"></i>
                <li><a href="javascript:;">MEUS DADOS</a></li></i>
            </ul>
        </div>
    </div>
</div>
<!--FIM BREADCRUMB-->

<div class="container">

    <div class="row">

        <div class="col-sm-3">

            <h1 class="title">MINHA CONTA</h1>

            <ul class="submenu">
                <li class="<?php echo ($this->layout()->routes['action'] == 'meus-dados') ? 'active' : null; ?>">
                    <a href="/conta/meus-dados"><i class="fa fa-caret-right"></i> Meus dados</a>
                </li>
                <li class="<?php echo ($this->layout()->routes['action'] == '') ? 'active' : null; ?>">
                    <a href="javascript:;"><i class="fa fa-caret-right"></i> Outro item de menu</a>
                </li>
            </ul>

        </div>

        <div class="col-sm-9">

            <h2 class="title">MEUS DADOS</h2>

            <form method="post" class="validate auto-values" data-values='<?php echo json_encode($this->data); ?>'>

                <div class="form-group text-left text-muted">
                    Nome ou Razão social: *<br/>
                    <input name="nome" type="text" class="form-control-login" autofocus="autofocus" />
                </div>

                <div class="form-group text-left text-muted">
                    CPF ou CNPJ: *<br/>
                    <input name="cpf_cnpj" type="text" class="form-control-login" onfocus="javascript:retirarFormatacao(this);" onblur="javascript:formatarCampo(this);" maxlength="14" />
                </div>

                <div class="form-group text-left text-muted">
                    Celular:<br/>
                    <input name="telefone" type="tel" class="form-control-login cellphone" />
                </div>

                <div class="form-group row login-submit">
                    <div class="col-sm-6">
                        <button data-dismiss="modal" type="submit" class="btn btn-login btn-xl">Atualizar</button>
                    </div>
                </div>

                <?php echo \Tropaframework\Security\NoCSRF::generate("content"); ?>
                <input type="hidden" name="method" value="meusDadosSave" />

            </form>

        </div>

    </div>

</div>