<div class="col-lg-12 col-md-12 titulo_perguntas_frequentes">
    <li><a href="#">PERGUNTAS FREQUENTES</a></li>
</div>

<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_01">
    Como realizar consultas?
</a>
<div id="faq_01" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>
<br><br>
<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_02">
    Cancelamento de serviços?
</a>
<div id="faq_02" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>
<br><br>
<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_03">
    Perdi minha senha. O que faço?
</a>
<div id="faq_03" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>

<br><br>

<div class="col-lg-12 col-md-12 titulo_perguntas_frequentes">
    <li><a href="#">PAGAMENTOS E VALORES</a></li>
</div>
<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_04">
    Quanto tempo demora a liberação após o pagamento?
</a>
<div id="faq_04" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>
<br><br>
<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_05">
    Quais são as formas de pagamento?
</a>
<div id="faq_05" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>
<br><br>
<i class="fa fa-caret-right"></i>&nbsp;
<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#faq_06">
    Como realizar consultas?
</a>
<div id="faq_06" class="accordion-body collapse" style="height: 0px;">
    <div class="accordion-inner">
        <p class="negrito">PESSOA FÍSICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>

        <p class="negrito">PESSOA JURÍDICA:</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor ligula, consectetur in tempus at, rhoncus at metus. Quisque efficitur in felis nec dignissim. Sed gravida ligula ut convallis tempor. Maecenas tempor mauris eu nisl vehicula dapibus. Morbi accumsan aliquet elit, et rhoncus ligula finibus ut.</p>
    </div>
</div>