<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Painel\Module'                        => __DIR__ . '/Module.php',
    'Painel\Controller\IndexController' => __DIR__ . '/src/Painel/Controller/IndexController.php',
);
