<!--LINHA NAV-->
<div class="hr_resultado">
    <hr>
</div>
<!--FIM LINHA NAV-->

<div class="col-lg-12 col-md-12 back_color_login">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="col-lg-4 col-md-4">
                <div class="tabela_1 tabela_condicao">
                    <div class="ambiente_seguro">
                        <img clas src="https://guerreiro.geofinder.tech/assets/application/img/ambiente_seguro.png">
                    </div>
                    <hr>
                    <table>
                        <tbody>
                        <tr>
                            <td><i class="fa fa-check-circle"></i></td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus arcu id nibh euismod molestie. Vestibulum a hendrerit sapien.</td>
                        </tr>
                        </tbody>
                    </table>
                    <hr>
                    <table>
                        <tbody>
                        <tr>
                            <td><i class="fa fa-check-circle"></i></td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus arcu id nibh euismod molestie. Vestibulum a hendrerit sapien.</td>
                        </tr>
                        </tbody>
                    </table>
                    <hr>
                    <img src="https://guerreiro.geofinder.tech/assets/application/img/pay_1.png">
                    <hr>
                    <img src="https://guerreiro.geofinder.tech/assets/application/img/pay_2.png">
                    <hr>
                    <div class="cartoes_credito">
                        <img src="https://guerreiro.geofinder.tech/assets/application/img/cartoes_credito.jpg">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 blc_tabela_planos">
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Standard</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Professional</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Business</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Gold</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Platinum</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
                <div class="tabela_1 tabela_preco">
                    <div class="titulo_tabela"><h1>Diamante</h1></div>
                    <hr>
                    <div class="preco_tabela">
                        <span class="moeda">R$</span>
                        <span class="valor">29</span>
                        <span class="centavos">,90</span>
                    </div>
                    <table class="table tabela-planos table-borderless">
                        <tbody class="no-border-x">
                        <tr>
                            <td><b>100</b> Consultas</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                        <tbody class="no-border-x">
                        <tr>
                            <td>Não expiram</td>
                            <td class="actions"><a href="#" class="icon"><i class="fa fa-check-circle"></i></a></td>
                        </tr>
                        </tbody>
                    </table>
                    <button data-dismiss="modal" type="submit" class="btn btn-planos">Comprar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!--TAB DOCUMENTOS FISCAIS-->
<!--<script>-->
<!--    function openPage(pageName,elmnt,color) {-->
<!--        var i, tabcontent, tablinks;-->
<!--        tabcontent = document.getElementsByClassName("tabcontent");-->
<!--        for (i = 0; i < tabcontent.length; i++) {-->
<!--            tabcontent[i].style.display = "none";-->
<!--        }-->
<!--        tablinks = document.getElementsByClassName("tablink");-->
<!--        for (i = 0; i < tablinks.length; i++) {-->
<!--            tablinks[i].style.backgroundColor = "";-->
<!--        }-->
<!--        document.getElementById(pageName).style.display = "block";-->
<!--        elmnt.style.backgroundColor = color;-->
<!--    }-->
<!---->
<!--    // Get the element with id="defaultOpen" and click on it-->
<!--    document.getElementById("defaultOpen").click();-->
<!--</script>-->