-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 17:30:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tropad80_concad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tropad80_concad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tropad80_concad` DEFAULT CHARACTER SET utf8 ;
USE `tropad80_concad` ;

-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_login` (
  `id_login` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `nivel` INT(1) NULL DEFAULT 1,
  `status` INT(1) NULL DEFAULT '1',
  `modificado` VARCHAR(45) NULL DEFAULT NULL,
  `criado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_login` INT(11) NOT NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `status` INT(1) NULL DEFAULT 1,
  `modificado` VARCHAR(45) NULL,
  `criado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_cc_usuario_cc_login_idx` (`id_login` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NULL,
  `servico` VARCHAR(255) NULL,
  `preco` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `status` INT(1) NULL DEFAULT 1,
  `modificado` VARCHAR(45) NULL,
  `criado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_consulta` (
  `id_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_login` INT(11) NOT NULL,
  `id_servico` INT(11) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_cc_consulta_cc_login1_idx` (`id_login` ASC) VISIBLE,
  INDEX `fk_cc_consulta_cc_servico1_idx` (`id_servico` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_pessoa_juridica` (
  `id_pessoa_juridica` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NULL,
  `razao_social` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `imagem` VARCHAR(255) NULL,
  `receita_federal` TEXT NULL,
  `simples_nacional` TEXT NULL,
  `sintegra` TEXT NULL,
  `suframa` TEXT NULL,
  `status` INT(1) NULL DEFAULT 1,
  `modificado` VARCHAR(45) NULL,
  `criado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa_juridica`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tropad80_concad`.`cc_pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tropad80_concad`.`cc_pessoa_fisica` (
  `id_pessoa_fisica` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `nascimento` VARCHAR(45) NULL,
  `receita_federal` TEXT NULL,
  `modificado` VARCHAR(45) NULL,
  `criado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa_fisica`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
