<!--LINHA NAV-->
<div class="hr_resultado">
    <hr>
</div>
<!--FIM LINHA NAV-->

<!--PÁGINA-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 pagina">
            <ul>
                <li><a href="#">HOME</a></li><i class="fa fa-angle-right"></i>
                <li><a href="#">COMPRAR CRÉDITO</a></li><i class="fa fa-angle-right"></i>
            </ul>
        </div>
    </div>
</div>
<!--FIM PÁGINA-->

<!--COMPRA DE CRÉDITO-->
<div class="container bloco_comprar">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="col-lg-6 col-md-6 comprar">
                <div class="col-lg-12 col-md-12 titulo_comprar">
                    <li><a href="#">COMPRAR</a></li>
                </div>
                <form name="qryform" id="qryform" method="post" action="mail.php" onsubmit="return(validate());" novalidate="novalidate">
                    <div class="form-group">
                        <label>Nome ou Razão social</label>
                        <input type="text" class="form-control" id="name" placeholder="Nome" name="name">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" id="name" placeholder="Email" name="email">
                    </div>
                    <div class="form-group">
                        <label>Confirmar seu email</label>
                        <input type="email" class="form-control" id="name" placeholder="Confirmar seu email" name="email">
                    </div>
                    <div class="form-group">
                        <label>Assunto</label>
                        <input type="text" class="form-control" id="name" placeholder="Assunto" name="subject">
                    </div>
                    <div class="form-group">
                        <label>CPF OU CNPJ</label>
                        <input type="text" class="form-control" id="name" placeholder="CPF OU CNPJ" name="subject">
                    </div>
                    <div class="form-group">
                        <label>TELEFONE</label>
                        <input type="text" class="form-control" id="name" placeholder="Telefone" name="subject">
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12 col-md-12 titulo_pagamento">
                            <li><a href="#">PAGAMENTO</a></li>
                        </div>
                        <label>Valor</label><br>
                        <select name="ctl00$ContentPlaceHolder1$DropDownValor" id="ContentPlaceHolder1_DropDownValor" class="valorcredito">
                            <option selected="selected" value="R$ 0,00"></option>
                            <option value="R$ 38,50">R$ 38,50</option>
                            <option value="R$ 50,00">R$ 50,00</option>
                            <option value="R$ 60,00">R$ 60,00</option>
                            <option value="R$ 70,00">R$ 70,00</option>
                            <option value="R$ 80,00">R$ 80,00</option>
                            <option value="R$ 90,00">R$ 90,00</option>
                            <option value="R$ 100,00">R$ 100,00</option>
                            <option value="R$ 200,00">R$ 200,00</option>
                            <option value="R$ 300,00">R$ 300,00</option>
                            <option value="R$ 400,00">R$ 400,00</option>
                            <option value="R$ 500,00">R$ 500,00</option>
                            <option value="R$ 600,00">R$ 600,00</option>
                            <option value="R$ 700,00">R$ 700,00</option>
                            <option value="R$ 800,00">R$ 800,00</option>
                            <option value="R$ 900,00">R$ 900,00</option>
                            <option value="R$ 1.000,00">R$ 1.000,00</option>
                            <option value="R$ 2.000,00">R$ 2.000,00</option>
                            <option value="R$ 3.000,00">R$ 3.000,00</option>
                            <option value="R$ 4.000,00">R$ 4.000,00</option>
                            <option value="R$ 5.000,00">R$ 5.000,00</option>
                            <option value="R$ 8.000,00">R$ 8.000,00</option>
                            <option value="R$ 10.000,00">R$ 10.000,00</option>
                        </select>

                    </div>

                </form>

                <label>Selecione a forma de pagamento</label>
                <ul class="nav nav-tabs img_cartao_credito">
                    <li class="liVisa"><a href="#pVisa" data-toggle="tab">
                            <img src="/assets/application/img/visa_comprar.png"></a>
                    </li>
                    <li class="liMastercard"><a href="#pMastercard" data-toggle="tab">
                            <img src="/assets/application/img/mastercard_comprar.png"></a>
                    </li>
                    <li class="liHipercard"><a href="#pHipercard" data-toggle="tab">
                            <img src="/assets/application/img/hipercard_comprar.png"></a>
                    </li>
                    <li class="liAmex"><a href="#pAmex" data-toggle="tab">
                            <img src="/assets/application/img/amex_comprar.png"></a>
                    </li>
                    <li class="liDiners"><a href="#pDiners" data-toggle="tab">
                            <img src="/assets/application/img/diners_comprar.png"></a>
                    </li>
                    <li class="liElo"><a href="#pElo" data-toggle="tab">
                            <img src="/assets/application/img/elo_comprar.png"></a>
                    </li>
                </ul>
                <button type="submit" class="btn btn-default">Finalizar a Compra</button>
            </div>

            <div class="col-lg-6 col-md-6 logo_serasa">
                <img src="/assets/application/img/serasa.jpg">
            </div>
        </div>
    </div>
</div>
<!--FIM COMPRA DE CRÉDITO-->