<?php
/**
 * @var $result \Model\Result\ResultPessoaFisica
 */
?>

<!--LINHA NAV-->
<div class="hr_resultado">
    <hr>
</div>
<!--FIM LINHA NAV-->

<!--PÁGINA-->
<div class="container">
    <div class="row">
        <div class="pagina">
            <ul>
                <li><a href="/">HOME</a></li><i class="fa fa-angle-right"></i>
                <li><a href="javascript:;">RESULTADO</a></li>
            </ul>
        </div>
    </div>
</div>
<!--FIM PÁGINA-->

<!--SECTION RESULTADO DA BUSCA-->
<div id="result" class="container text-muted">

    <div class="row">

        <div class="col-sm-5">

<!--            <form class="search validate" method="POST" action="/consulta-e-servicos">-->
<!--                <input type="text" name="cpf" value="--><?php //echo $result->getCpf(); ?><!--">-->
<!--                <button class="btn" type="submit"><i class="fa fa-search"></i></button>-->
<!--                <input type="hidden" name="method" value="consultarCpf" />-->
<!--                --><?php //echo \Tropaframework\Security\NoCSRF::generate('content'); ?>
<!--            </form>-->

            <div class="image">
                <img src="/assets/application/img/predio.jpg" />
            </div>

            <h1 class="title">Sobre <?php echo $result->getNome(); ?></h1>
            <p class="text-muted">Nenhuma informação sobre a descrição dessa pessoa no momento!</p>

<!--            <hr />-->
<!---->
<!--            <ul class="list">-->
<!--                <li>-->
<!--                    <i class="fa fa-globe"></i>-->
<!--                    --><?php //echo $result->getCnpj(); ?>
<!--                </li>-->
<!--                <li>-->
<!--                    <i class="fa fa-check-circle"></i>-->
<!--                    --><?php //echo $result->getNomeFantasia(); ?>
<!--                </li>-->
<!--                <li>-->
<!--                    <i class="fa fa-phone"></i>-->
<!--                    --><?php //echo $result->getTelefone(); ?>
<!--                </li>-->
<!--                <li>-->
<!--                    <i class="fa fa-envelope"></i>-->
<!--                    --><?php //echo $result->getEmail(); ?>
<!--                </li>-->
<!--                <li>-->
<!--                    <i class="fa fa-map-marker"></i>-->
<!--                    --><?php //echo $result->getEnderecoCompleto(); ?>
<!--                </li>-->
<!--            </ul>-->

        </div>

        <div class="col-sm-7">

            <h2 class="title-featured">
                <i class="fa fa-building"></i>
                <?php echo $result->getNome(); ?>
            </h2>

            <div class="tabs">
                <button id="tabdefault" class="tabclick tabactive" onclick="openPage('tab1', this, '#fff')">Receita Federal</button>
            </div>

            <div id="tab1" class="tabcontent">

                <h4 class="title">INFORMAÇÕES DA CONSULTA</h4>
                <hr/>

                <p><b>CPF:</b> <?php echo $result->getCpf(); ?></p>
                <p><b>Data de nascimento:</b> <?php echo $result->getDataNascimento(); ?></p>
                <p><b>Situação cadastral:</b> <?php echo $result->getSituacaoCadastral(); ?></p>
                <p><b>Data da inscrição:</b> <?php echo $result->getDataInscricao(); ?></p>
                <p><b>Dígito verificador:</b> <?php echo $result->getDigitoVerificador(); ?></p>
                <p><b>Comprovante:</b> <?php echo $result->getComprovante(); ?></p>

            </div>

            <ul class="links">
                <li><a href="javascript:;">SALVAR CONSULTA</a></li>
                <li><a href="javascript:;">ENVIAR VIA SMS</a></li>
                <li><a href="javascript:;">PESQUISAR VÍNCULOS</a></li>
            </ul>

        </div>

    </div>

</div>
<!--FIM SECTION RESULTADO DA BUSCA-->

<script type="text/javascript">
    function openPage(pageName,elmnt,color) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tabclick");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].style.backgroundColor = "";
        }
        document.getElementById(pageName).style.display = "block";
        elmnt.style.backgroundColor = color;


        $('.tabactive').removeClass('tabactive');
        elmnt.classList.add('tabactive');
    }
    document.getElementById("tabdefault").click();
</script>