<!doctype html>
<html>
<head>
    <base href="/" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink(); ?>

    <!-- Bootstrap -->
    <link href="https://guerreiro.geofinder.tech/assets/application/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://guerreiro.geofinder.tech/assets/application/font-awesome-4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://guerreiro.geofinder.tech/assets/application/css/style.css">
    <link rel="stylesheet" href="https://guerreiro.geofinder.tech/assets/application/css/animate.css">

    <!-- Google Fonts Montserrat -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Js Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://guerreiro.geofinder.tech/assets/application/js/wow.min.js"></script>
    <script>new WOW().init();</script>
    <script src="https://guerreiro.geofinder.tech/assets/application/bootstrap/bootstrap.min.js"></script>
    <?php echo $this->headScript(); ?>

</head>

<body>

    <?php echo $this->message(); ?>

    <!--LINHA AZUL CABEÇALHO-->
    <div class="container linha_cabecalho">
        <div class="row">
            <hr>
        </div>
    </div>
    <!--FIM LINHA AZUL CABEÇALH0-->

    <!--NAVEGAÇÃO-->
    <div id="myNavbar" class="navbar navbar-default" role="navigation">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="https://guerreiro.geofinder.tech/assets/application/img/logo_concad.png"></a>
            </div>

            <div class="navbar-collapse collapse menu_nav">
                <ul class="nav navbar-nav">
                    <li><a id="home" href="/" class="<?php echo ($this->layout()->routes['controller'] == 'index') ? 'active' : null; ?>">HOME</a></li>
                    <li><a href="/planos" class="<?php echo ($this->layout()->routes['controller'] == 'planos') ? 'active' : null; ?>">COMPRAR CRÉDITO</a></li>
                    <li><a href="/consulta-e-servicos" class="<?php echo ($this->layout()->routes['controller'] == 'consulta-e-servicos') ? 'active' : null; ?>">CONSULTA E SERVIÇOS</a></li>
<!--                    <li><a href="#" class="--><?php //echo ($this->layout()->routes['controller'] == 'ferramentas') ? 'active' : null; ?><!--">FERRAMENTAS</a></li>-->
                    <li><a href="/fale-conosco" class="<?php echo ($this->layout()->routes['controller'] == 'fale-conosco') ? 'active' : null; ?>">FALE CONOSCO</a></li>

                    <?php if( \Model\ModelLogin::loginCheck($this->layout()->me) ): ?>

                        <li id="auth-menu">
                            <a href="javascript:;" class=""><i class="fa fa-user"></i> Olá <?php echo $this->layout()->me->apelido; ?></a>

                            <ul>
                                <li><a href="/conta/meus-dados">Meus dados</a></li>
                                <li><a href="/login/logout"><i class="fa fa-power-off"></i> Não é você? Sair</a></li>
                            </ul>
                        </li>

                    <?php else: ?>

                        <li><a id="sua_conta" href="/cadastro" class="<?php echo ($this->layout()->routes['controller'] == 'cadastro') ? 'active' : null; ?>">CRIAR CONTA</a></li>
                        <li><a id="login" href="/login" class="<?php echo ($this->layout()->routes['controller'] == 'login') ? 'active' : null; ?>">ACESSAR</a></li>

                    <?php endif; ?>
                </ul>

            </div>

        </div>

    </div>
    <!--FIM NAVEGAÇÃO-->

    <?php echo $this->content; ?>

    <!--CONSULTE FOOTER-->
    <div class="container consulte_footer">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="col-lg-8 col-md-8">
                    <div class="col-lg-12 col-md-12 info_footer">
                        <div class="col-lg-4 col-md-4 como_funciona_footer">Como funciona a consulta?</div>
                        <div class="col-lg-4 col-md-4 detalhe_relatorio_footer">Detalhes do Relatório</div>
                        <div class="col-lg-4 col-md-4 quando_utilizar_footer">Quando utilizar?</div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <a href="/consulta-e-servicos"><button type="button" class="consult_footer">CONSULTE</button></a>
                </div>
            </div>
        </div>
    </div>
    <!--FIM CONSULTE FOOTER-->

    <!--FOOTER-->
    <div class="container footer">
        <div class="row">
            <div class="col-lg-12 col-md-12 bloco_footer">
                <div class="col-lg-2 col-md-2">
                    <img src="https://guerreiro.geofinder.tech/assets/application/img/logo_concad_branco.png">
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="col-lg-12 col-md-12">
                        <div class="col-lg-6 col-md-6">
                            <h1>Atendimento ao Usuário</h1>
                            <p>
                                (11) 3111-6555 das
                                9h às 18h ATENDIMENTO@CONCAD.COM.BR
                            </p>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <h1>Endereço</h1>
                            <p>
                                Rua Alvares Penteado, 97, 4º andar, Centro,
                                São Paulo - Capital. • CEP 01232-011
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3">
                    <div class="col-lg-12 col-md-12">
                        <div class="col-lg-6 col-md-6 logo_protesto">
                            <img src="https://guerreiro.geofinder.tech/assets/application/img/logo_protesto_bem.png">
                        </div>
                        <div class="col-lg-6 col-md-6 logo_IEPTB">
                            <img src="https://guerreiro.geofinder.tech/assets/application/img/logo_IEPTB.png">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--FIM FOOTER-->

    <!--TODO OS DIREITOS-->
    <div class="container todos_direito">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <hr>
                <p>CONCAD | Consulta cadastral   •   2020   •   Todos os direitos reservados.</p>
            </div>
        </div>
    </div>
    <!--FIM TODO OS DIREITOS-->

</body>
</html>