<!doctype html>
<html>
<head>
    <base href="/" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink(); ?>

    <!-- Bootstrap -->
    <link href="/assets/application/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/assets/application/font-awesome-4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/application/css/style.css">
    <link rel="stylesheet" href="/assets/application/css/animate.css">

    <!-- Google Fonts Montserrat -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Js Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/assets/application/js/wow.min.js"></script>
    <script>new WOW().init();</script>
    <script src="/assets/application/bootstrap/bootstrap.min.js"></script>
    <?php echo $this->headScript(); ?>
</head>

<body class="back_color">

    <?php echo $this->message(); ?>
    <?php echo $this->content; ?>

</body>
</html>