<div style="width:100%; background-color:#eee;">

	<table style="font-family:'Arial'; font-size:14px; color:#777; margin:auto;" border="0" cellspacing="0">
		
		<!-- HEADER -->
		<tr>
	    	<td style="width:620px; background-color:#fff; border-bottom:5px solid #1f8cc6; text-align: center;">
	    		<a href="http://<?php echo $_SERVER["HTTP_HOST"]; ?>">
	    			<img src="http://<?php echo $_SERVER['HTTP_HOST']; ?>/assets/application/img/logo_concad.png" style="border:0; width:200px;" />
	    		</a>
	    	</td>
	    </tr>
		
	    <!-- CONTENT -->
	    <tr>
	    	<td style="width:620px; background-color:#fff; padding:20px 0; font-size:14px; border-bottom:5px solid #1f8cc6;">
	    		<?php echo $content; ?>
	    	</td>
	    </tr>
	    
	</table>

</div>