<div style="width:100%; background-color:#eee;">

	<table style="font-family:'Arial'; font-size:14px; color:#777; margin:auto;" border="0" cellspacing="0">
		
		<tr>
			<td>
				<img src="http://<?php echo $_SERVER['HTTP_HOST']; ?>/assets/bag365/img/email/topo-mail.jpg" style="width:100%; border:0;" />
			</td>
	    </tr>
		
	    <tr>
	    	<td style="width:600px; background-color:#fff; padding:20px 0; font-size:14px;">
	    		<?php echo $content; ?>
	    	</td>
	    </tr>
	    
	</table>

</div>