<div class="col-lg-4 col-md-4 info_preco_consulta">

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Completa CPF</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Completa CNPJ</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Monitoramento de CPF</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Monitoramento de CNPJ</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Cheques</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Pendência</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Cheques + Pendências</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Cheques + Pendências + Protestos</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

    <div class="col-lg-12 col-md-12 bloco_precos_consulta">
        <div class="col-lg-10 col-md-10 icon_circle">
            <div class="col-lg-1 col-md-1">
                <i class="fa fa-circle"></i>
            </div>
            <div class="col-lg-5 col-md-5" style="padding: 0;">
                <p>Telefones por CPF/CNPJ</p>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <p>R$38,50</p>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 hr_consulta">
        <hr>
    </div>

</div>