<!--LINHA NAV-->
<div class="hr_resultado">
    <hr>
</div>
<!--FIM LINHA NAV-->

<!--PÁGINA-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 pagina">
            <ul>
                <li><a href="/">HOME</a></li><i class="fa fa-angle-right"></i>
                <li><a href="javascript:;">FALE CONOSCO</a></li>
            </ul>
        </div>
    </div>
</div>
<!--FIM PÁGINA-->

<div class="container bloco_perguntas">

    <div class="row">

        <div class="col-lg-12 col-md-12">

            <!--PERGUNTAS FREQUENTES -->
            <div class="col-lg-6 col-md-6 perguntas">

                <?php echo $this->partial("partials/faq"); ?>

            </div>

            <!--FORMULÁRIO -->
            <div class="col-lg-6 col-md-6 mensagem">

                <div class="col-lg-12 col-md-12 titulo_mensagem">
                    <li><a href="#">MENSAGEM</a></li>
                </div>

                <form id="qryform" method="POST" class="validate">

                    <div class="form-group">
                        <label>Nome *</label>
                        <input type="text" class="form-control" name="nome" autofocus="autofocus">
                    </div>

                    <div class="form-group">
                        <label>E-mail *</label>
                        <input type="text" class="form-control" name="email">
                    </div>

                    <div class="form-group">
                        <label>Telefone *</label>
                        <input type="tel" class="form-control cellphone" name="telefone">
                    </div>

                    <div class="form-group">
                        <label>Assunto *</label>
                        <input type="text" class="form-control" name="assunto">
                    </div>

                    <div class="form-group">
                        <label>Mensagem *</label>
                        <textarea name="mensagem" class="form-control" placeholder="Escreva sua mensagem..."></textarea>
                    </div>

                    <?php echo \Tropaframework\Security\NoCSRF::generate('content'); ?>
                    <button type="submit" class="btn btn-default">Enviar</button>
                    <input type="hidden" name="method" value="send" />

                </form>

            </div>

        </div>

    </div>

</div>