<!--HEADER-->
<div class="container header">
    <div class="row">
        <div class="col-lg-12 col-md-12 bloco_cpf_cnpj">
            <div id="text-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="carousel-content">
                            <div class="col-lg-3 col-md-3 info_cpf">
                                <h1>CPF <span>DE TERCEIROS</span></h1>
                                <h2>R$ 35</h2>
                                <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_onda.png">
                                <p>
                                    Saiba se o prestador de<br>
                                    serviço que você quer<br>
                                    contratar é de confiança.<br>
                                </p>
                                <button type="button" class="consulte">CONSULTE</button>
                                <p class="ver_ex">Ver exemplo</p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="col-lg-3 col-md-3 info_cnpj">
                            <h1>CNPJ <span>DE TERCEIROS</span></h1>
                            <h2>R$ 35</h2>
                            <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_onda.png">
                            <p>
                                Antes de fechar negócio com<br>
                                uma empresa, confira se ela<br>
                                pode trazer dores de cabeça.<br>
                            </p>
                            <button type="button" class="consulte">CONSULTE</button>
                            <p class="ver_ex">Ver exemplo</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12 footer_header">
            <div class="col-lg-4 col-md-4 como_funciona">Como funciona a consulta?</div>
            <div class="col-lg-4 col-md-4 detalhe_relatorio">Detalhes do Relatório</div>
            <div class="col-lg-4 col-md-4 quando_utilizar">Quando utilizar?</div>
        </div>

    </div>
</div>
<!--FIM HEADER-->

<!--CONSULTA RÁPIDA-->
<div class="col-lg-12 col-md-12 consulta_rapida">
    <div class="row">
        <div class="col-lg-6 col-md-6 consulta_cpf_cnpj">
            <h2>RÁPIDO, SEGURO E CONFIÁVEL</h2>
            <h1>Consulta Rápida</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adiasdp.</p>
            <nav class="navbar navbar-light bg-light">
                <form class="form-inline">
                    <input class="form-control-buscar mr-sm-2" type="search" placeholder="CPF ou CNPJ" aria-label="Search">
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Buscar</button>
                </form>
            </nav>
            <span class="counter-count">191589657</span>
            <p class="consulta_realizada">Consultas realizadas pelo ConCad</p>
        </div>
        <div class="col-lg-6 col-md-6 consulta_info">
            <div class="col-lg-12 col-md-12">
                <div class="col-lg-12 col-md-12 consulta_icon">
                    <div class="col-lg-6 col-md-6">
                        <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_buscar.png">
                        <p>
                            Escolha se quer consultar<br>
                            um CPF ou CNPJ.
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_paper.png">
                        <p>
                            Acesse o reatório assim que<br>
                            concluir a compra.
                        </p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="col-lg-6 col-md-6">
                        <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_cell.png">
                        <p>
                            Realize o pagamento online<br>
                            via cartão de crédito.
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/icon_pdf.png">
                        <p>
                            Receba em seu e-mail o<br>
                            relátório em PDF.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--FIM CONSULTA RÁPIDA-->

<!--EMPRESAS CADASTRADAS-->
<div class="col-lg-12 col-md-12 empresa_cadastrada">
    <div class="row">
        <h2>LOREM DOLOR SIT AMET</h2>
        <h1>
            Faça consultas em segundos e obtenha informações<br>
            de milhões de empresas
        </h1>
        <p>Lorem ipsum dolor sit amet, consectetur adiasdp.</p>
        <h3 class="counter-count">39242415</h3>
        <span>EMPRESAS CADASTRADAS</span>
    </div>
    <hr>
</div>
<!--FIM EMPRESAS CADASTRADAS-->

<!--MAN-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 man">
            <div class="col-lg-3 col-md-3">
                <h1>Cancelamento<br>de Protesto</h1>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Meus Pedidos</p>
                <a href="/planos"><button type="button" class="comprar_credito">COMPRAR CRÉDITO</button></a>
            </div>
            <div class="col-lg-4 col-md-4">
                <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/man.jpg">
            </div>
            <div class="col-lg-5 col-md-5 valores_consulta">
                <div class="col-lg-12 col-md-12">
                    <h1>Valores e<br>Tipos de Consulta</h1>
                    <div class="col-lg-9 col-md-9">
                        <p>Completa CPF</p>
                        <hr>
                        <p>Completa CNPJ</p>
                        <hr>
                        <p>Monitoramento de CPF</p>
                        <hr>
                        <p>Cheques</p>
                        <hr>
                        <p>Pendências</p>
                        <hr>
                        <p>Cheques + Pendências</p>
                        <hr>
                        <p>Cheques + Pendências + Protestos</p>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <p>R$ 35,00</p>
                        <hr>
                        <p>R$ 35,00</p>
                        <hr>
                        <p>R$ 35,00</p>
                        <hr>
                        <p>R$ 39,90</p>
                        <hr>
                        <p>R$ 2,99</p>
                        <hr>
                        <p>R$ 7,95</p>
                        <hr>
                        <p>R$ 9,70</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--FIM MAN-->

<!--MAN-MOBILE-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 man_mobile">
            <div class="col-lg-3 col-md-3">
                <h1>Cancelamento<br>de Protesto</h1>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Pedido de Cancelamento</p>
                <hr>
                <p>Meus Pedidos</p>
                <button type="button" class="comprar_credito">COMPRAR CRÉDITO</button>
            </div>
            <div class="col-lg-4 col-md-4">
                <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/man.jpg">
            </div>
            <div class="col-lg-5 col-md-5 valores_consulta_mobile">
                <div class="col-lg-12 col-md-12">
                    <h1>Valores e<br>Tipos de Consulta</h1>
                    <div class="col-lg-9 col-md-9">
                        <p>Completa CPF | R$ 35,00</p>
                        <hr>
                        <p>Completa CNPJ | R$ 35,00</p>
                        <hr>
                        <p>Monitoramento de CPF | R$ 35,00</p>
                        <hr>
                        <p>Cheques | R$ 39,90</p>
                        <hr>
                        <p>Pendências | R$ 2,99</p>
                        <hr>
                        <p>Cheques + Pendências | R$ 7,95</p>
                        <hr>
                        <p>Cheques + Pendências + Protestos | R$ 9,70</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--FIM MAN-MOBILE-->

<!--CARTÕES-->
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 cartoes">
            <img src="https://guerreiro.geofinder.tech/CONCAD/public/assets/application/img/cartoes.jpg">
        </div>
    </div>
</div>
<!--FIM CARTÕES-->

<!--NUMBER COUNTER-->
<script>
$('.counter-count').each(function () {
    $(this).prop('Counter',0).animate({
        Counter: $(this).text()
    }, {
        duration: 5000,
        easing: 'swing',
        step: function (now) {
            $(this).text(Math.ceil(now));
        }
    });
});
</script>