<div class="row">

	<div class="col-lg-12">
	
		<div class="card">
		
			<div class="card-body">
			
				<table class="table table-responsive-sm table-hover table-outline">
				
					<thead class="thead-light">
						<tr>
                            <th>Código</th>
                            <th>Plano</th>
                            <th>Valor</th>
							<th style="width:60px"></th>
                        </tr>
					</thead>
					
                    <tbody>
                    	<?php foreach( $this->result['result'] as $row ): ?>
                        <tr>
                            <td><?php echo $row['id_tipo']; ?></td>
                            <td><?php echo $row['tipo']; ?></td>
                            <td>R$ <?php echo \Tropaframework\Helper\Convert::toReal($row['valor']); ?></td>
                            <td>
                            	<div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdown-menu-right" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    	<i class="fa fa-cogs"></i>
                                    </button>

                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="/painel/<?php echo $this->layout()->routes['controller'];?>/form?id=<?php echo $row['id_tipo']; ?>">
                                            Editar
                                        </a>
                                    </div>
                                </div>
                        	</td>
                        </tr>
                        <?php endforeach; ?>
					</tbody>
					
				</table>
			
    		</div>
    		
    	</div>
    	
    </div>
    
</div>